server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Cache-Control "no-store" always;
        try_files $uri $uri/ =404;
    }

    location /payloads/ {
        add_header Cache-Control "no-store" always;
        types { application/octet-stream elf bin; }
    }
}
